apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simpleservice-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simpleservice
    spec:
      containers:
      - name: simpleservice
        image: luebken/simpleservice
        ports:
        - containerPort: 8080
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.0.1"
