apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simpleservice-deploy-a
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simpleservice-a
    spec:
      containers:
      - name: simpleservice
        image: luebken/simpleservice
        ports:
        - containerPort: 8080
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.0.1"
        - name: SIMPLE_SERVICE_DOWNSTREAM_SERVICES
          value: "http://simpleservice-service-b.mdl.svc.cluster.local/endpoint-b,http://simpleservice-service-b.mdl.svc.cluster.local/last-endpoint,http://simpleservice-service-b.mdl.svc.cluster.local/last-endpoint"